name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build an image from Dockerfile
      run: |
        docker build -t ${{secrets.DOCKER_USERNAME}}/homework:latest -t ${{secrets.DOCKER_USERNAME}}/homework:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{secrets.DOCKER_USERNAME}}/homework:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os, library'
        severity: 'CRITICAL,HIGH'
    
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker push
      run: docker push -a ${{secrets.DOCKER_USERNAME}}/homework
